### PR TITLE
feat: save mapping of old and new indices

### PR DESCRIPTION
**Pull request by KRiedmiller**
* Update_dict mapping old to new indices gets saved as json. Necessary to know where produced radicals actually are.
* more consistent argument naming 
* Progress output
* Better file handling, output dir now consistent for all produced outputs
* Paths get resolved

### CODE REVIEW

**Comment by ehhartmann** [comment]
I think at one point we agreed to call the topology object `top` and paths etc. top_path, ... (see runmanager). The naming between the cli options and the modify_top function is then different but I would accept that for the benefit of having a simple cli naming and keeping the naming consistent between main kimmdy and kimmdy tools

**Comment by ehhartmann** [comment]
I think something like `gro_str` is a descriptive variable name for the python UI. What does the PEP guru @jmbuhr say about this case?

**Comment by jmbuhr** [comment]
`_str` sounds to me like we are expecting the while file as a string (like passed from the command line via stdin), but we are expecting a filepath. So I would still call it path, even though it is not a `pathlib.Path` instance (it does get converte to one anyways).

**Comment by jmbuhr** [comment]
There are varied opinions on having types in variable names. Some practices stem from a time where a particular low level programming language had only one datatype so you'd add a type as a prefix to the name (Hungarian Notation), but this is redundant with a type system. I think in a dynamically typed language like python it adds value where a value can exist in two types and may change at runtime i.e. in cases where you really want to make a type explicit to the reader.

In this case, at least in my mind, `_path` doesn't necessarily indicate a _type_, but rather the _usage_. However, if all arguments to the CLI function are file paths anyways, or clearly identifiable as something else (like a boolean flag), we may as well drop the `_path` for the CLI in favor of being concise.

**Comment by KRiedmiller** [comment]
Yes, as the function accepts str and paths, and everything that works like it, there is no need for a type in the name.  
`_path`, `_file`, or `_filename` are fine, but imo not necessary. what should that gro be, if not a file. The user will not parse the top by themselves, so it must be a file. I feel like there is little ambiguity there.

**Comment by ehhartmann** [comment]
I think it could easily happen that someone passes a topology object as top. Also you would have `top` and `topol` in the code which is more ambiguous than `top` and `top_filename`

**Comment by jmbuhr** [comment]
not with type annotations, that's what they are for in this case.

**Review by ehhartmann — APPROVED** [review]

**Pull request merged**
