### PR TITLE
Clean modify top api

### LINKED ISSUE #377: fix modify_top args
modify_top api has some issues:

* radicals is a required field in python, but not in the cmd
* radicals in the cmd is a single string, but there can be multiple radicals
* 'Namespace' object has no attribute 'grofile' (fixed in 9f9b162)

### PR DESCRIPTION
**Pull request by KRiedmiller**
Resolves #377

`radicals` variable unchanged downstream from 'modify_top'

Now, the python and cmd line api are the same

### CODE REVIEW

**Comment by ehhartmann** [comment]
this should fail some tests

**Comment by ehhartmann** [comment]
and radicals = None is not a good default

**Review by ehhartmann — CHANGES_REQUESTED** [review]
see comments

**Comment by KRiedmiller** [comment]
To summarize:

The `radicals` argument was mend to control the radical searching behavior of KIMMDY, on top of providing a list of radicals. In normal KIMMDY yaml input, this works by providing nothing, an empty list, or a filled list.  
Here, with a cmd interface, this does not work well, as one can't supply an empty list intuitively.
Therefore, I added the `search_amber_rad`  variable. If the ff is not amber, on needs to set this to false.  
For amber, if radicals are provided, they are used, no search is performed.

**Review by ehhartmann — APPROVED** [review]
fine like this. there will be changes in the future

**Review by jmbuhr — APPROVED** [review]

**Pull request merged**
