### PR TITLE
fix: update scheme url in examples and docs

### PR DESCRIPTION
**Pull request by KRiedmiller**
No need anymore for specifying schema paths in `kimmdy.yml` files.

@jmbuhr I guess, Neovim still needs the schema url in the config or does it pull from the store automatically? I left the Neovim settings in our docs for now.

### CODE REVIEW

**Comment by jmbuhr** [comment]
For now yes, but I can replace the instructions with https://github.com/b0o/SchemaStore.nvim for the same effect.

**Comment by jmbuhr** [comment]
ah, nvm, no need for an additional plugin. It's built into the yaml language server configuration already.

**Comment by KRiedmiller** [comment]
Perfect! Not sure why the store-plugin then mentiones YAML again, but I read it also like that.  
So we can also leave out the neovim config at that point completely, correct?

**Comment by jmbuhr** [comment]
I examples for both configs just in case, since we have no control over the defaults and I want to make sure the schema store is actually enabled.

**Pull request merged**
