### PR TITLE
Feat/improve edissoc

### PR DESCRIPTION
**Pull request by ehhartmann**

### CODE REVIEW

**Comment by ehhartmann** [comment]
Needs to be validated with the kimmdy-reactions plugin

**Comment by ehhartmann** [comment]
Ready for review!

FAILED tests/test_integration.py::test_integration_pull[test_integration/triplehelix_pull] - AssertionError: assert 12 == 11
FAILED tests/test_integration.py::test_integration_whole_run[test_integration/charged_peptide_homolysis_hat_naive] - RuntimeError: Encountered torsion that is neither proper nor improper: (95, 99, 97, 98)

============== 2 failed, 93 passed, 2 warnings in 997.08s (0:16:37) =============

**Review by KRiedmiller — APPROVED** [review]
Looks good, ready to merge :+1:

**Comment by ehhartmann** [comment]
This doesn't fix some issues with specbonds and bonds between residues in general

**Pull request merged**
